#! /bin/sh
set -e

PIDFILE=/var/run/fernbedienung.pid
SCRIPT=/usr/lib/fernbedienung/service.py
LOGFILE=/var/log/fernbedienung.log

# source function library
. /etc/init.d/functions

case "$1" in
  start)
	echo "Starting Fernbedienung"
	start-stop-daemon \
		--quiet \
		--start \
		--background \
		--make-pidfile \
		--pidfile $PIDFILE \
		--startas /usr/bin/python3 -- $SCRIPT --log $LOGFILE
	;;
  stop)
        echo "Stopping Fernbedienung"
	start-stop-daemon \
		--quiet \
		--stop \
		--pidfile $PIDFILE \
		--signal SIGINT
	;;

  restart)
        echo "Restarting Fernbedienung"
	start-stop-daemon \
		--quiet \
		--stop \
		--oknodo \
		--pidfile $PIDFILE \
		--signal SIGINT
	sleep 1
	start-stop-daemon \
		--quiet \
		--start \
		--background \
		--make-pidfile \
		--pidfile $PIDFILE \
		--startas /usr/bin/python3 -- $SCRIPT --log $LOGFILE
	;;

  status)
	status /usr/bin/python3
	exit $?
  ;;

  *)
	echo "Usage: /etc/init.d/fernbedienung {start|stop|status|restart}"
	exit 1
esac

exit 0
